// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7tbkvMVIo6k6gVYl77KSks0RYkoVu63s',
    appId: '1:867127803675:web:dd27ddc3c249bee3d09dbe',
    messagingSenderId: '867127803675',
    projectId: 'nti-grad-project',
    authDomain: 'nti-grad-project.firebaseapp.com',
    storageBucket: 'nti-grad-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfs7YVemqLboiJQoOUOXF35BkpgLwU-mI',
    appId: '1:867127803675:android:9567903b5e7a36dcd09dbe',
    messagingSenderId: '867127803675',
    projectId: 'nti-grad-project',
    storageBucket: 'nti-grad-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcXjL4cY3Y93bOcxCyjJPa-nsgVwK3KYc',
    appId: '1:867127803675:ios:28e8013b2677539cd09dbe',
    messagingSenderId: '867127803675',
    projectId: 'nti-grad-project',
    storageBucket: 'nti-grad-project.firebasestorage.app',
    iosClientId: '867127803675-mo18n60eisg92i476im1f00ro6ofg1n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectNtiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcXjL4cY3Y93bOcxCyjJPa-nsgVwK3KYc',
    appId: '1:867127803675:ios:28e8013b2677539cd09dbe',
    messagingSenderId: '867127803675',
    projectId: 'nti-grad-project',
    storageBucket: 'nti-grad-project.firebasestorage.app',
    iosClientId: '867127803675-mo18n60eisg92i476im1f00ro6ofg1n1.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectNtiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7tbkvMVIo6k6gVYl77KSks0RYkoVu63s',
    appId: '1:867127803675:web:a11370662506e76cd09dbe',
    messagingSenderId: '867127803675',
    projectId: 'nti-grad-project',
    authDomain: 'nti-grad-project.firebaseapp.com',
    storageBucket: 'nti-grad-project.firebasestorage.app',
  );

}